Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
r = request_header_url("Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) Gecko/20100101 Firefox/15.0.1", "https://pta.trunojoyo.ac.id/c_search/byprod/10")
soup = parse_website(r)
prettify_web_structure(soup)
table = get_content_table(soup, "div", {"id":"wrapper"})

pagination = table.findAll("a", attrs = {"class":"pag_button"})
total_pages = int(pagination[LAST_INDEX]["href"].split("/")[LAST_INDEX])

papers = []
for pages in range(FIRST_INDEX, total_pages + INCREMENT_BY_ONE):

    url_link = "https://pta.trunojoyo.ac.id/c_search/byprod/10"
    id_prodi = url_link.split("/")[LAST_INDEX]
    nama_prodi = ""
    if (id_prodi == "10"):
        nama_prodi = "Teknik Informatika"

    r_pages = request_header_url("Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) Gecko/20100101 Firefox/15.0.1", f"{url_link}/{pages}")
    soup_pages = parse_website(r_pages)
    prettify_web_structure(soup_pages)
    table_pages = get_content_table(soup_pages, "div", {"id":"wrapper"})

    for article_row in table_pages.findAll("a", attrs = {"class":"gray button"}):
        r_article_row = request_header_url("Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) Gecko/20100101 Firefox/15.0.1", article_row["href"])
        soup_article_row = parse_website(r_article_row)
        prettify_web_structure(soup_article_row)
        table_article_row = get_content_table(soup_article_row, "li", {"data-id":"id-1", "data-cat":"#luxury"})
        article_row_title = table_article_row.find('a', attrs = {"class":"title", "href":"#"}).string
        article_row_abstract = table_article_row.find('p', attrs = {"align":"justify"}).string
        nim = str(article_row["href"]).split("/")[LAST_INDEX]
        papers.append([
            nim,
            article_row_title,
            article_row_abstract,
            nama_prodi
        ])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mgaierror[0m                                  Traceback (most recent call last)
[0;32m/usr/local/lib/python3.10/dist-packages/urllib3/connection.py[0m in [0;36m_new_conn[0;34m(self)[0m
[1;32m    202[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 203[0;31m             sock = connection.create_connection(
[0m[1;32m    204[0m                 [0;34m([0m[0mself[0m[0;34m.[0m[0m_dns_host[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mport[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py[0m in [0;36mcreate_connection[0;34m(address, timeout, source_address, socket_options)[0m
[1;32m     59[0m [0;34m[0m[0m
[0;32m---> 60[0;31m     [0;32mfor[0m [0mres[0m [0;32min[0m [0msocket[0m[0;34m.[0m[0mgetaddrinfo[0m[0;34m([0m[0mhost[0m[0;34m,[0m [0mport[0m[0;34m,[0m [0mfamily[0m[0;34m,[0m [0msocket[0m[0;34m.[0m[0mSOCK_STREAM[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     61[0m         [0maf[0m[0;34m,[0m [0msocktype[0m[0;34m,[0m [0mproto[0m[0;34m,[0m [0mcanonname[0m[0;34m,[0m [0msa[0m [0;34m=[0m [0mres[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.10/socket.py[0m in [0;36mgetaddrinfo[0;34m(host, port, family, type, proto, flags)[0m
[1;32m    954[0m     [0maddrlist[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 955[0;31m     [0;32mfor[0m [0mres[0m [0;32min[0m [0m_socket[0m[0;34m.[0m[0mgetaddrinfo[0m[0;34m([0m[0mhost[0m[0;34m,[0m [0mport[0m[0;34m,[0m [0mfamily[0m[0;34m,[0m [0mtype[0m[0;34m,[0m [0mproto[0m[0;34m,[0m [0mflags[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    956[0m         [0maf[0m[0;34m,[0m [0msocktype[0m[0;34m,[0m [0mproto[0m[0;34m,[0m [0mcanonname[0m[0;34m,[0m [0msa[0m [0;34m=[0m [0mres[0m[0;34m[0m[0;34m[0m[0m

[0;31mgaierror[0m: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

[0;31mNameResolutionError[0m                       Traceback (most recent call last)
[0;32m/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py[0m in [0;36murlopen[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)[0m
[1;32m    790[0m             [0;31m# Make the request on the HTTPConnection object[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 791[0;31m             response = self._make_request(
[0m[1;32m    792[0m                 [0mconn[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py[0m in [0;36m_make_request[0;34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)[0m
[1;32m    491[0m                 [0mnew_e[0m [0;34m=[0m [0m_wrap_proxy_error[0m[0;34m([0m[0mnew_e[0m[0;34m,[0m [0mconn[0m[0;34m.[0m[0mproxy[0m[0;34m.[0m[0mscheme[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 492[0;31m             [0;32mraise[0m [0mnew_e[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    493[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py[0m in [0;36m_make_request[0;34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)[0m
[1;32m    467[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 468[0;31m                 [0mself[0m[0;34m.[0m[0m_validate_conn[0m[0;34m([0m[0mconn[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    469[0m             [0;32mexcept[0m [0;34m([0m[0mSocketTimeout[0m[0;34m,[0m [0mBaseSSLError[0m[0;34m)[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py[0m in [0;36m_validate_conn[0;34m(self, conn)[0m
[1;32m   1096[0m         [0;32mif[0m [0mconn[0m[0;34m.[0m[0mis_closed[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1097[0;31m             [0mconn[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1098[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/urllib3/connection.py[0m in [0;36mconnect[0;34m(self)[0m
[1;32m    610[0m         [0msock[0m[0;34m:[0m [0msocket[0m[0;34m.[0m[0msocket[0m [0;34m|[0m [0mssl[0m[0;34m.[0m[0mSSLSocket[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 611[0;31m         [0mself[0m[0;34m.[0m[0msock[0m [0;34m=[0m [0msock[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_new_conn[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    612[0m         [0mserver_hostname[0m[0;34m:[0m [0mstr[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mhost[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/urllib3/connection.py[0m in [0;36m_new_conn[0;34m(self)[0m
[1;32m    209[0m         [0;32mexcept[0m [0msocket[0m[0;34m.[0m[0mgaierror[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 210[0;31m             [0;32mraise[0m [0mNameResolutionError[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mhost[0m[0;34m,[0m [0mself[0m[0;34m,[0m [0me[0m[0;34m)[0m [0;32mfrom[0m [0me[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    211[0m         [0;32mexcept[0m [0mSocketTimeout[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameResolutionError[0m: <urllib3.connection.HTTPSConnection object at 0x7d8b0b09b760>: Failed to resolve 'pta.trunojoyo.ac.id' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

[0;31mMaxRetryError[0m                             Traceback (most recent call last)
[0;32m/usr/local/lib/python3.10/dist-packages/requests/adapters.py[0m in [0;36msend[0;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[1;32m    485[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 486[0;31m             resp = conn.urlopen(
[0m[1;32m    487[0m                 [0mmethod[0m[0;34m=[0m[0mrequest[0m[0;34m.[0m[0mmethod[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py[0m in [0;36murlopen[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)[0m
[1;32m    844[0m [0;34m[0m[0m
[0;32m--> 845[0;31m             retries = retries.increment(
[0m[1;32m    846[0m                 [0mmethod[0m[0;34m,[0m [0murl[0m[0;34m,[0m [0merror[0m[0;34m=[0m[0mnew_e[0m[0;34m,[0m [0m_pool[0m[0;34m=[0m[0mself[0m[0;34m,[0m [0m_stacktrace[0m[0;34m=[0m[0msys[0m[0;34m.[0m[0mexc_info[0m[0;34m([0m[0;34m)[0m[0;34m[[0m[0;36m2[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py[0m in [0;36mincrement[0;34m(self, method, url, response, error, _pool, _stacktrace)[0m
[1;32m    514[0m             [0mreason[0m [0;34m=[0m [0merror[0m [0;32mor[0m [0mResponseError[0m[0;34m([0m[0mcause[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 515[0;31m             [0;32mraise[0m [0mMaxRetryError[0m[0;34m([0m[0m_pool[0m[0;34m,[0m [0murl[0m[0;34m,[0m [0mreason[0m[0;34m)[0m [0;32mfrom[0m [0mreason[0m  [0;31m# type: ignore[arg-type][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    516[0m [0;34m[0m[0m

[0;31mMaxRetryError[0m: HTTPSConnectionPool(host='pta.trunojoyo.ac.id', port=443): Max retries exceeded with url: /c_search/byprod/10 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7d8b0b09b760>: Failed to resolve 'pta.trunojoyo.ac.id' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

[0;31mConnectionError[0m                           Traceback (most recent call last)
[0;32m<ipython-input-5-11b978f78ca3>[0m in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0;31m [0mr[0m [0;34m=[0m [0mrequest_header_url[0m[0;34m([0m[0;34m"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) Gecko/20100101 Firefox/15.0.1"[0m[0;34m,[0m [0;34m"https://pta.trunojoyo.ac.id/c_search/byprod/10"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0msoup[0m [0;34m=[0m [0mparse_website[0m[0;34m([0m[0mr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mprettify_web_structure[0m[0;34m([0m[0msoup[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mtable[0m [0;34m=[0m [0mget_content_table[0m[0;34m([0m[0msoup[0m[0;34m,[0m [0;34m"div"[0m[0;34m,[0m [0;34m{[0m[0;34m"id"[0m[0;34m:[0m[0;34m"wrapper"[0m[0;34m}[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;32m<ipython-input-4-69bfe4d136e2>[0m in [0;36mrequest_header_url[0;34m(header, url_website)[0m
[1;32m      4[0m [0;32mdef[0m [0mrequest_header_url[0m[0;34m([0m[0mheader[0m[0;34m,[0m [0murl_website[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0mheaders[0m [0;34m=[0m [0;34m{[0m[0;34m'User-Agent'[0m[0;34m:[0m [0mheader[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m     [0;32mreturn[0m [0mrequests[0m[0;34m.[0m[0mget[0m[0;34m([0m[0murl[0m[0;34m=[0m[0murl_website[0m[0;34m,[0m [0mheaders[0m[0;34m=[0m[0mheaders[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0;34m[0m[0m
[1;32m      8[0m [0;32mdef[0m [0mparse_website[0m[0;34m([0m[0mrequest[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/requests/api.py[0m in [0;36mget[0;34m(url, params, **kwargs)[0m
[1;32m     71[0m     """
[1;32m     72[0m [0;34m[0m[0m
[0;32m---> 73[0;31m     [0;32mreturn[0m [0mrequest[0m[0;34m([0m[0;34m"get"[0m[0;34m,[0m [0murl[0m[0;34m,[0m [0mparams[0m[0;34m=[0m[0mparams[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     74[0m [0;34m[0m[0m
[1;32m     75[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/requests/api.py[0m in [0;36mrequest[0;34m(method, url, **kwargs)[0m
[1;32m     57[0m     [0;31m# cases, and look like a memory leak in others.[0m[0;34m[0m[0;34m[0m[0m
[1;32m     58[0m     [0;32mwith[0m [0msessions[0m[0;34m.[0m[0mSession[0m[0;34m([0m[0;34m)[0m [0;32mas[0m [0msession[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 59[0;31m         [0;32mreturn[0m [0msession[0m[0;34m.[0m[0mrequest[0m[0;34m([0m[0mmethod[0m[0;34m=[0m[0mmethod[0m[0;34m,[0m [0murl[0m[0;34m=[0m[0murl[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     60[0m [0;34m[0m[0m
[1;32m     61[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/requests/sessions.py[0m in [0;36mrequest[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)[0m
[1;32m    587[0m         }
[1;32m    588[0m         [0msend_kwargs[0m[0;34m.[0m[0mupdate[0m[0;34m([0m[0msettings[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 589[0;31m         [0mresp[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0msend[0m[0;34m([0m[0mprep[0m[0;34m,[0m [0;34m**[0m[0msend_kwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    590[0m [0;34m[0m[0m
[1;32m    591[0m         [0;32mreturn[0m [0mresp[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/requests/sessions.py[0m in [0;36msend[0;34m(self, request, **kwargs)[0m
[1;32m    701[0m [0;34m[0m[0m
[1;32m    702[0m         [0;31m# Send the request[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 703[0;31m         [0mr[0m [0;34m=[0m [0madapter[0m[0;34m.[0m[0msend[0m[0;34m([0m[0mrequest[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    704[0m [0;34m[0m[0m
[1;32m    705[0m         [0;31m# Total elapsed time of the request (approximately)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/requests/adapters.py[0m in [0;36msend[0;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[1;32m    517[0m                 [0;32mraise[0m [0mSSLError[0m[0;34m([0m[0me[0m[0;34m,[0m [0mrequest[0m[0;34m=[0m[0mrequest[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    518[0m [0;34m[0m[0m
[0;32m--> 519[0;31m             [0;32mraise[0m [0mConnectionError[0m[0;34m([0m[0me[0m[0;34m,[0m [0mrequest[0m[0;34m=[0m[0mrequest[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    520[0m [0;34m[0m[0m
[1;32m    521[0m         [0;32mexcept[0m [0mClosedPoolError[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mConnectionError[0m: HTTPSConnectionPool(host='pta.trunojoyo.ac.id', port=443): Max retries exceeded with url: /c_search/byprod/10 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7d8b0b09b760>: Failed to resolve 'pta.trunojoyo.ac.id' ([Errno -2] Name or service not known)"))

